# Generated by Django 5.0.1 on 2024-01-24 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_match_professor_student_servicestat_drivestat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='drivestat',
            old_name='total_drives',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='drivestat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='servicestat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='type2stat',
            name='player',
        ),
        migrations.AddField(
            model_name='drivestat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicestat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type2stat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drivestat',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicestat',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='type2stat',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('player1_games', models.IntegerField()),
                ('player2_games', models.IntegerField()),
                ('player1_sets', models.IntegerField()),
                ('player2_sets', models.IntegerField()),
                ('is_tiebreaker', models.BooleanField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.match')),
            ],
        ),
    ]
